### ISSUE TITLE
Distributed training hangs after "Initializing distributed" message

### ISSUE THREAD

**Issue by mathigatti** [NVIDIA/tacotron2#311]
Hi, after running this
```
python3.5 -m multiproc train.py --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True
```

I get the program stucked on this point
```
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
master_weights         : True
patch_torch_functions  : False
cast_model_type        : torch.float16
loss_scale             : dynamic
opt_level              : O2
keep_batchnorm_fp32    : True
enabled                : True
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
master_weights         : True
patch_torch_functions  : False
cast_model_type        : torch.float16
loss_scale             : dynamic
opt_level              : O2
keep_batchnorm_fp32    : True
enabled                : True
Epoch: 0
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
```

I read some old suggestions pointing out to delete distribted.dpt but that file hasn't been generated. I also tried replacing distributed.py with the APEX distributed.py but it looks like that fix doesn't work anymore either. Do you know what might be causing the problem?

**Comment by mathigatti** [comment]
I'm using a google VM with Debian 9.12 and CUDA 10.1

I have python3.5 and those libraries
pytorch==1.4.0
matplotlib==2.1.0
tensorflow-gpu==1.14.0
numpy==1.17.0
inflect==0.2.5
librosa==0.6.0
scipy==1.0.0
Unidecode==1.0.22

**Comment by siliang625** [comment]
any update? im using it in docker container with torch==1.3.1+cpu

**Comment by mathigatti** [comment]
I fixed it but I'm not sure how. It seems to be a problem with the package versions, after running those commands inside a conda environment it worked.

```
conda install pytorch==1.0.0 torchvision==0.2.1 cuda100 -c pytorch
conda install --file requirements. txt
python -m pip install numpy==1.14.*
python -m pip install tensorflow==1.14.0
pip install --upgrade torch
pip install tensorboard
```

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
