### ISSUE TITLE
CUDA Runtime Error: Out of Memory

### ISSUE THREAD

**Issue by MrBreadWater** [NVIDIA/tacotron2#33]
I finally got all the errors resolved, but then this new one came up:
`RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58`

Here is the full log:
`~/tacotron2$ python3 train.py --output_directory=outdir --log_directory=logdir
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
/home/mrbreadwater/tacotron2/layers.py:35: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
/home/mrbreadwater/tacotron2/layers.py:15: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  gain=torch.nn.init.calculate_gain(w_init_gain))
Epoch: 0
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 291, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 216, in train
    y_pred = model(x)
  File "/home/mrbreadwater/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrbreadwater/tacotron2/model.py", line 510, in forward
    encoder_outputs, targets, memory_lengths=input_lengths)
  File "/home/mrbreadwater/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrbreadwater/tacotron2/model.py", line 403, in forward
    decoder_input)
  File "/home/mrbreadwater/tacotron2/model.py", line 363, in decode
    attention_weights_cat, self.mask)
  File "/home/mrbreadwater/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrbreadwater/tacotron2/model.py", line 77, in forward
    attention_hidden_state, processed_memory, attention_weights_cat)
  File "/home/mrbreadwater/tacotron2/model.py", line 60, in get_alignment_energies
    processed_query + processed_attention_weights + processed_memory))
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58`

I'm using a GTX 1050 Ti. Anything I can do to fix it?

EDIT: I'm running Ubuntu 18.04

**Comment by rafaelvalle** [comment]
Try decreasing batch size.

**Comment by MrBreadWater** [comment]
I did, all the way down to 16, but that didn't change anything. I can go
lower, but that seems suspiciously low.

**Comment by rafaelvalle** [comment]
I don't know from memory but I think the GTX 1050 TI has 4gb of memory, thus you should use a batch of samples. Please try with batch size 12 and let us know.

**Comment by rafaelvalle** [comment]
Try batch size 8.

**Comment by tatamyans** [comment]
out of memory error is gone, but python crashes after saving model :
Unhandled exception at 0x0000000076FAA0F2 (ntdll.dll) in python.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x0000000000123FF8).

python 3.5, 3.6 same thing
maybe unrelated

**Comment by rafaelvalle** [comment]
@tatamyans can you provide a full error trace?

**Comment by tatamyans** [comment]
sorry, can't provide full trace now, maybe later, thanks

**Comment by gsoul** [comment]
```
/home/soul/projects/nv-tacotron/tacotron2/layers.py:35: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
/home/soul/projects/nv-tacotron/tacotron2/layers.py:15: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  gain=torch.nn.init.calculate_gain(w_init_gain))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-82530a2f6baf> in <module>()
      1 checkpoint_path = "/home/soul/projects/nv-tacotron/tacotron2/outdir/checkpoint_80000"
----> 2 model = load_model(hparams)
      3 try:
      4     model = model.module
      5 except:

/home/soul/projects/nv-tacotron/tacotron2/train.py in load_model(hparams)
     78 
     79 def load_model(hparams):
---> 80     model = Tacotron2(hparams).cuda()
     81     if hparams.fp16_run:
     82         model = batchnorm_to_float(model.half())

/home/soul/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in cuda(self, device)
    247             Module: self
    248         """
--> 249         return self._apply(lambda t: t.cuda(device))
    250 
    251     def cpu(self):

/home/soul/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    174     def _apply(self, fn):
    175         for module in self.children():
--> 176             module._apply(fn)
    177 
    178         for param in self._parameters.values():

/home/soul/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    180                 # Tensors stored in modules are graph leaves, and we don't
    181                 # want to create copy nodes, so we have to unpack the data.
--> 182                 param.data = fn(param.data)
    183                 if param._grad is not None:
    184                     param._grad.data = fn(param._grad.data)

/home/soul/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in <lambda>(t)
    247             Module: self
    248         """
--> 249         return self._apply(lambda t: t.cuda(device))
    250 
    251     def cpu(self):

RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25
```

I get this when I try to do inference on 1080ti.

Training works fine on separate gpu with batch size of 40 all other settings are default. Dataset is LJSpeech-1.1

@rafaelvalle could you please advise here?

**Comment by gsoul** [comment]
Hm, perhaps I figured this out: PyTorch demanded GPU0 for inference. And as training was happening on in at the time - it gave OOM error.  could produce some speech after I stopped training.

**Comment by rafaelvalle** [comment]
@gsoul yes, one can run into OOM if multiple sources are requesting memory from the same GPU. If you want to train and do inference at the same time, you could do inference on the CPU...

**Comment by gsoul** [comment]
No, I have 2 * 1080ti in my machine. And used CUDA_VISIBLE_DEVICES to separate inference and training into separate gpus, but was getting error above, until stopped training on gpu0.

**Comment by gsoul** [comment]
After thinking for some time - perhaps not. I ran:
```
CUDA_VISIBLE_DEVICE=1 /home/soul/anaconda3/bin/ipython notebook --no-browser --port=8889
```

But such command limits only ipython process rather than python process that communicates with gpus...

**Comment by codemandosch** [comment]
Hi,

I seem to have the same problem as @tatamyans . The program just shuts down after printing "saving model". More specifically it seems to be when executing the line:

loss = criterion(y_pred, y)

**No exception is raised however. I go into windows event logs and it shows me this error:**

Faulting application name: python.exe, version: 3.6.5150.1013, time stamp: 0x5abd3210
Faulting module name: ntdll.dll, version: 10.0.15063.608, time stamp: 0x8274fd8b
Exception code: 0xc00000fd
Fault offset: 0x0000000000030ee5
Faulting process id: 0x13bc
Faulting application start time: 0x01d4144c054bb6b2
Faulting application path: C:\Users\***\AppData\Local\conda\conda\envs\taco2\python.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: c2322300-de32-4f5b-92dc-64556a66035c
Faulting package full name: 
Faulting package-relative application ID: 

**And this information:**

Fault bucket 1756424923264366124, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: python.exe
P2: 3.6.5150.1013
P3: 5abd3210
P4: ntdll.dll
P5: 10.0.15063.608
P6: 8274fd8b
P7: c00000fd
P8: 0000000000030ee5
P9: 
P10: 

Attached files:

Report.wer: 

Version=1
EventType=APPCRASH
EventTime=131752606400776280
ReportType=2
Consent=1
UploadTime=131752606424959155
ReportStatus=268435456
ReportIdentifier=8895e8da-aae3-4e65-8b86-0100b2401d09
IntegratorReportIdentifier=c2322300-de32-4f5b-92dc-64556a66035c
Wow64Host=34404
NsAppName=python.exe
AppSessionGuid=000013bc-0002-00d4-b2b6-4b054c14d401
TargetAppId=W:0006c155cb6c1dec33f065e9b49a8b0b7f0a00000000!0000a113a4428bdfc2dcda474f24c25bb070f2407c8f!python.exe
TargetAppVer=2018//03//29:18:36:00!0!python.exe
BootId=4294967295
TargetAsId=3933
Response.BucketId=63008810f06359cf8860132969d0b62c
Response.BucketTable=4
Response.LegacyBucketId=1756424923264366124
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=python.exe
Sig[1].Name=Application Version
Sig[1].Value=3.6.5150.1013
Sig[2].Name=Application Timestamp
Sig[2].Value=5abd3210
Sig[3].Name=Fault Module Name
Sig[3].Value=ntdll.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.15063.608
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=8274fd8b
Sig[6].Name=Exception Code
Sig[6].Value=c00000fd
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000030ee5
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.15063.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=da15
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=da15a370eccf3aac589f01a49e310e57
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=13c8
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=13c84f4595611a55236cfdd9d616887a
UI[2]=C:\Users\per\AppData\Local\conda\conda\envs\taco2\python.exe
LoadedModule[0]=C:\Users\per\AppData\Local\conda\conda\envs\taco2\python.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
...
LoadedModule[238]=C:\WINDOWS\SYSTEM32\dxgi.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Python
AppPath=C:\Users\per\AppData\Local\conda\conda\envs\taco2\python.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=0920103314D9505A1A73B6FD36D5EC01
MetadataHash=417055776

**Comment by rafaelvalle** [comment]
Closing due to inactivity.

**Comment by Ala2dz** [comment]
I fixed this by reducing the batch size to 32 in hparam:
``` batch_size=32 ```

**Comment by ErfolgreichCharismatisch** [comment]
Tutorial: Training on GPU with Colab, Inference with CPU on Server [here](https://github.com/NVIDIA/tacotron2/issues/467).

**Comment by one1ine** [comment]
Hello everyone, I am having the same GPU memory issue.
1. Using Nvidia A40 with 46GB memory
2. Using a batchsize of 8!
3. Using a custom dataset of 40hrs with a sampling rate of 22050, which is like 6GB of data.
The training is initially running fine but just around finishing 3 epochs, the memory error pops up and stops the training.

Since im already using a batchsize of 8, i dont think lowering it any lower would beneficial.
That said, I'm thinking of trying to clear the cache (torch.cuda.empty_cache()) at the end of every epoch because i think its accumulating and filling up the cache since the memory is consistently popping up after 3 epoch.

Will let you know if it works out.


UPDATE (23/04/14):
So I'm running the training on server using slurm, and after doing the above the slurm job automatically gets killed. So seems clearing the cache after each epoch doesn't seem to work...
